spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhouwen
    url: jdbc:mysql://localhost/mysql?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: flase
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
